INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Regents','Algebra I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Regents','Geometry');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Regents','Algebra II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Regents','Precalculus');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'AP','AP Calc AB');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'AP','AP Calc BC');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Linear Algebra');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Multivariable Calculus');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'AP','AP Stats');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Junior Math Analysis');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Intermediate Math Analysis');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Senior Math Team');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Number Theory');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Graph Theory');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (1,'Elective','Intro to Math Research');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Regents','Living Environment');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'AP','AP Bio');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Regents','Living Environment Lab');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Elective','Genetics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'AP','AP Psych');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Elective','Bioorganic Chemistry');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'AP','APES');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Elective','Intro to Neuro');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Elective','Human Anatomy');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (2,'Elective','Environmental Sustainability');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Regents','Chemistry');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'AP','AP Chem');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Regents','Chem Lab');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Forensics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Weston');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Organic Chemistry Pharmacy Seminar');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Regents','Physics Lab');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Regents','Physics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'AP','AP Physics 1');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'AP','AP Physics 2');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'AP','AP Physics C Mech');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'AP','AP Physics C E&M');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Modern Physics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Astronomy');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Quantitative Analysis');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Organic Chem');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','Biochemistry');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (3,'Elective','MICA');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'AP','AP CSP');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'AP','AP CSA');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','IT Infrastructure & Big Data');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Mobile App Development');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Cybersecurity');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Digital Electronics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Robotics Engineering I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Robotics Engineering II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','PLTW CIM');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','PLTW CEA');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Mechatronics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','PLTW PoE');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Flight School');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Aerospace Engineering');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Digital Design');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Building Materials and Fabrication');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Architectural Design & Modeling');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Engineering Statics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','AutoCAD Certification');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','American Concrete Institute Certification');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Surveying Certification');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (4,'Elective','Analog Electronics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Regents','English 9');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Regents','English 10');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Regents','English 11');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'AP','AP Capstone Seminar');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'AP','AP Lang');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'AP','AP Lit');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'AP','AP Capstone Research');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Yearbook');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Creative Writing');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Drama');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Film and Lit');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Graphic Novels');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Journalism');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','LLD');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','MHS');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Sci-Fi');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (5,'Elective','Journalism');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Regents','Health');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Regents','PE');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Advanced Weight Training');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Backyard Games');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Badminton and Pickleball');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Basketball');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Capoeira');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Dance');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Golf');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Lacrosse');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Soccer and Team Handball');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Salsa I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Salsa II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Spin');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Swimming');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Volleyball');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Weight Training');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (6,'Elective','Yoga');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Regents','DDP');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'AP','AP Music Theory');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Set Design');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Basic Strings');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Concert Band');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Concert Choir');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Intermediate Orchestra');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Jazz Band');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Junior Band');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Orchestra');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','String Orchestra');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Symphonic Band');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Treble Choir');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Tech Chorale');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Spring Musical');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Stageworks');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Fundamentals of Product Design');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Methods of Fabrication');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Advanced Modelling');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Adobe Visual Design');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Studio Art');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','AP Studio Art');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Digital Animation');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Video Game Design');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Adobe Digital Video');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Architectural Drawing');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (7,'Elective','Inventor Certification');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Spanish I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Spanish II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Spanish III');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Spanish IV');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP Spanish Lang');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP Spanish Lit');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Italian I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Italian II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Italian III');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP Italian');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','German I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','German II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','German III');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP German');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','French I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','French II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','French III');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP French');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Mandarin I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Mandarin II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Mandarin III');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'Regents','Mandarin IV');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (8,'AP','AP Chinese');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Regents','Pre-AP World');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Regents','Global Studies');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP World');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Euro');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Regents','United States History');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','APUSH');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Macro');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Micro');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP African American Studies');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Art History');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Business Principles');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Gov');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','AP Comp Gov');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'AP','APHUG');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Regents','Economics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Regents','Participation in Government');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Physical Anthropology');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Cultural Anthropology');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Dollars and Sense');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Social Science Research');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Sociology');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Crim Law');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Crim Pro');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Civil Law');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Constitutional Law I');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Constitutional Law II');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Legal Research');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Principles of Accounting');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Finance and Investments');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Intro to Business Law');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Virtual Enterprise');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Financial Literacy');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (9,'Elective','Civics');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (10,'Elective','Freshman Student Leadership');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (10,'Elective','Sophomore Student Leadership');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (10,'Elective','Junior Student Leadership');
INSERT INTO Courses (DepartmentID,CourseType,CourseName) VALUES (10,'Elective','Senior Student Leadership');
