INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Algebra I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Geometry');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Algebra II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Precalculus');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Calc AB');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Calc BC');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Linear Algebra');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Multivariable Calculus');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Stats');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Junior Math Analysis');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Intermediate Math Analysis');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Senior Math Team');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Number Theory');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Graph Theory');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Intro to Math Research');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Living Environment');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Bio');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Living Environment Lab');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Genetics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Psych');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Bioorganic Chemistry');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','APES');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Intro to Neuro');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Human Anatomy');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Environmental Sustainability');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Chemistry');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Chem');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Chem Lab');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Forensics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Weston');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Organic Chemistry Pharmacy Seminar');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Physics Lab');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Physics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Physics 1');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Physics 2');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Physics C Mech');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Physics C E&M');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Modern Physics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Astronomy');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Quantitative Analysis');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Organic Chem');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Biochemistry');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','MICA');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP CSP');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP CSA');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','IT Infrastructure & Big Data');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Mobile App Development');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Cybersecurity');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Digital Electronics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Robotics Engineering I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Robotics Engineering II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','PLTW CIM');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','PLTW CEA');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Mechatronics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','PLTW PoE');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Flight School');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Aerospace Engineering');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Digital Design');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Building Materials and Fabrication');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Architectural Design & Modeling');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Engineering Statics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','AutoCAD Certification');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','American Concrete Institute Certification');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Surveying Certification');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Analog Electronics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','English 9');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','English 10');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','English 11');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Capstone Seminar');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Lang');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Lit');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Capstone Research');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Yearbook');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Creative Writing');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Drama');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Film and Lit');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Graphic Novels');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Journalism');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','LLD');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','MHS');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Sci-Fi');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Journalism');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Health');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','PE');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Advanced Weight Training');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Backyard Games');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Badminton and Pickleball');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Basketball');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Capoeira');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Dance');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Golf');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Lacrosse');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Soccer and Team Handball');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Salsa I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Salsa II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Spin');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Swimming');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Volleyball');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Weight Training');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Yoga');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','DDP');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Music Theory');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Set Design');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Basic Strings');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Concert Band');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Concert Choir');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Intermediate Orchestra');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Jazz Band');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Junior Band');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Orchestra');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','String Orchestra');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Symphonic Band');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Treble Choir');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Tech Chorale');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Spring Musical');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Stageworks');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Fundamentals of Product Design');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Methods of Fabrication');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Advanced Modelling');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Adobe Visual Design');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Studio Art');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','AP Studio Art');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Digital Animation');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Video Game Design');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Adobe Digital Video');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Architectural Drawing');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Inventor Certification');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Spanish I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Spanish II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Spanish III');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Spanish IV');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Spanish Lang');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Spanish Lit');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Italian I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Italian II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Italian III');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Italian');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','German I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','German II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','German III');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP German');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','French I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','French II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','French III');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP French');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Mandarin I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Mandarin II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Mandarin III');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Mandarin IV');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Chinese');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Pre-AP World');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Global Studies');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP World');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Euro');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','United States History');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','APUSH');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Macro');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Micro');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP African American Studies');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Art History');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Business Principles');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Gov');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','AP Comp Gov');
INSERT INTO Courses (CourseType,CourseName) VALUES ('AP','APHUG');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Economics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Regents','Participation in Government');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Physical Anthropology');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Cultural Anthropology');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Dollars and Sense');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Social Science Research');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Sociology');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Crim Law');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Crim Pro');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Civil Law');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Constitutional Law I');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Constitutional Law II');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Legal Research');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Principles of Accounting');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Finance and Investments');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Intro to Business Law');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Virtual Enterprise');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Financial Literacy');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Civics');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Freshman Student Leadership');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Sophomore Student Leadership');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Junior Student Leadership');
INSERT INTO Courses (CourseType,CourseName) VALUES ('Elective','Senior Student Leadership');
